name: Sphinx

on:
  workflow_dispatch:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.8'
          cache: 'pip'
          cache-dependency-path: pyproject.toml
      - name: Install dependencies
        run: |
          python -m pip install -U pip
          pip install -e .[doc]
      - name: Build HTML
        run: make html
        working-directory: docs
      - name: Upload artifacts
        uses: actions/upload-pages-artifact@v1
        with:
          path: docs/_build/html/

  deploy:
    needs: build
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
